### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#10]
When I try to send I have such an error:
"... uploading weight
Error uploading file to Garmin Connect:  social profile not found in HTML
exiting after  1  tries"

**Comment by RobertWojtowicz** [comment]
It looks like something has changed, people here have also reported a problem:
https://github.com/kochka/WeightLogger/issues/53

**Comment by RobertWojtowicz** [comment]
Hey, here the author commented on issue of the problem:
https://github.com/kochka/WeightLogger/issues/53#issuecomment-761882249

Could you verify and fix the program?

**Comment by davidkroell** [comment]
Hey @RobertWojtowicz I created a new hotfix release [v2.0.1](https://github.com/davidkroell/bodycomposition/releases/tag/v2.0.1) where this is fixed.

I'm currently waiting for the pull request abrander/garmin-connect#5 to finally draft a new release and close this issue.

Thanks for the information so I could fix this very fast.

Regards,
David

**Comment by RobertWojtowicz** [comment]
Hi, @davidkroell 

The hotfix is working, I can see there is a pull request on 25.01, can you make a new release ? :)

**Comment by davidkroell** [comment]
New release with updated dependencies is available.

https://github.com/davidkroell/bodycomposition/releases/tag/v2.1.0
