### ISSUE TITLE
Can you add Caloric Intake?

### ISSUE THREAD

**Issue by gabamnml** [davidkroell/bodycomposition#11]
Can you add this param?
Thanks

**Comment by davidkroell** [comment]
Hello @gabamnml, even though the base library [tormoder/fit](https://github.com/tormoder/fit) I am using here does support caloric intake, I have not found a solution to show this inside of Garmin Connect after importing.

It seems that Garmin does not display the weight values together with the calories.

It would also help to have a better understanding of your requirements and where you want these values to show up - since I haven't found the right place yet.

Regards,
David

**Comment by gabamnml** [comment]
Hello @davidkroell do you see the caloric intake in this weight view?
![Screen Shot 2021-04-28 at 12 23 32](https://user-images.githubusercontent.com/379450/116438631-a1152400-a81c-11eb-882d-1063ad843ee1.png)
Thanks

**Comment by davidkroell** [comment]
No, I do not see this in my Garmin Connect overview. 

Nevertheless I've added the caloric intake to the CLI interface.
Could you please try it out? I've created a new (pre) release [v2.2.0-rc1](https://github.com/davidkroell/bodycomposition/releases/tag/v2.2.0-rc1) for that.

Thank you for your feedback,
David

**Comment by gabamnml** [comment]
Hello @davidkroell many thanks for the pre release. what is the tag to add caloric intake to test?

**Comment by davidkroell** [comment]
You can either use `-c` or `--calories`, as the help page for the command shows:
```bash
$ .\bodycomposition.exe upload -h
Upload your body composition values to Garmin Connect

Usage:
  bodycomposition upload [flags]

Aliases:
  upload, u, add

Flags:
  -b, --bone float              Set your bone mass in percent
  -c, --calories float          Set your caloric intake
  -e, --email string            Email of the Garmin account
  -f, --fat float               Set your fat in percent
  -h, --help                    help for upload
      --hydration float         Set your hydration in percent
      --max-tries int           Set maximum retry count, if error occur in Garmin Connect api (default 1)
      --metabolic-age float     Set your metabolic age
  -m, --muscle float            Set your muscle mass in percent
  -p, --password string         Password of the Garmin account
      --physique-rating float   Set your physique rating (valid values: 1-9)
  -t, --unix-timestamp int      Set the timestamp of the measurement (default -1)
      --visceral-fat float      Set your visceral fat rating (valid values: 1-60)
  -w, --weight float            Set your weight in kilograms (default -1)
```

**Comment by RobertWojtowicz** [comment]
@gabamnml Do you also have a problem with uplod to Garmin: https://github.com/davidkroell/bodycomposition/issues/13
I can't wait to check the functionality from version 2.2.0-rc1 with Xiaomi scale :-)

**Comment by davidkroell** [comment]
@gabamnml any updates on this?

**Comment by RobertWojtowicz** [comment]
Unfortunately it does not work (I compiled a new version of the fix base: https://github.com/abrander/garmin-connect/pull/13):
![obraz](https://user-images.githubusercontent.com/19271127/121674625-948a1980-cab2-11eb-80ec-4ea09d5b8baa.png)

**Comment by davidkroell** [comment]
@RobertWojtowicz I created a new release [2.2.0-rc2](https://github.com/davidkroell/bodycomposition/releases/tag/v2.2.0-rc2) to reflect the changes made in #13.

I know, it does not work for me either. There must be something wrong with a dependent library.

But for me it does not even show the **Caloric Intake** column on the right side.

**Comment by RobertWojtowicz** [comment]
@davidkroell 

In the last version you uploaded is the version with an EOF error (you compiled with the garmin-connect library without a fix ).
I checked the package bodycomposition_2.2.0-rc2_Linux_x86_64.tar.gz
It works on my compilation with fix (I manually edited the Activity.go file in the latest version of the garmin-connect library) .

Maybe report the problem to the author of dependent library - tormoder/fit ? 

Best Regards,
Robert

**Comment by gabamnml** [comment]
Sorry for the delay @davidkroell but dont work. Here is the output
![Screen Shot 2021-07-19 at 17 19 29](https://user-images.githubusercontent.com/379450/126228863-375a4dc9-5832-4322-8b65-b178e00daa5f.png)

**Comment by gabamnml** [comment]
Hello @davidkroell sorry for the delay. The RC dont work here is the output.
If I put password after the flags
![Screen Shot 2021-07-19 at 17 26 34](https://user-images.githubusercontent.com/379450/126229706-2bce92ba-83b8-4f3e-8e6f-24b5ea66b432.png)
If I send password as a param flag:
![Screen Shot 2021-07-19 at 17 26 08](https://user-images.githubusercontent.com/379450/126229957-9b6624fd-2db7-4db0-9551-eb5284d3867f.png)

**Comment by RobertWojtowicz** [comment]
@gabamnml As I wrote above, compiled version includes old version without the patch.
If you are using Linux I suggest you download the correct version from me: https://github.com/RobertWojtowicz/miscale2garmin/blob/master/bodycomposition

**Comment by vegancorr** [comment]
It does not show the uploaded calories in Garmin Connect, it's ignored. I used the binary file. 

Maybe the "Caloric Intake" value from the "Weight" section is from the "Calories in/Out" section (MyFitnessPal import) and cannot be uploaded?
