### ISSUE TITLE
Error uploading file to Garmin Connect:  Garmin SSO returned "403 Forbidden"                                                        

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#13]
Tested on version 2.1.0 and 2.2.0-rc1

Have they changed something in Garmin again?
Isn't that the case ?: https://github.com/abrander/garmin-connect/issues/2

**Comment by RobertWojtowicz** [comment]
OK, is needed bypass Cloudflare's anti-bot page:
https://github.com/abrander/garmin-connect/issues/11
https://github.com/petergardfjall/garminexport/issues/79

Sample project:
https://github.com/VeNoMouS/cloudscraper

**Comment by RobertWojtowicz** [comment]
@abrander create fix: https://github.com/abrander/garmin-connect/commit/9f867d3d6af9745d0bd876a7b4df1e14eaa960f5
@davidkroell can you compile a new version? 

Best Regards,
Robert

**Comment by davidkroell** [comment]
Hi @RobertWojtowicz,

this issue is now resolved but I'm now getting and EOF error from Garmin Connect.

**Comment by RobertWojtowicz** [comment]
> Hi @RobertWojtowicz,
> 
> this issue is now resolved but I'm now getting and EOF error from Garmin Connect.

Hi @davidkroell 

I have the same problem, I reported it to @abrander.
