### ISSUE TITLE
Upload problem [solved]

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#14]
Hi @davidkroell 

I get the following message when uploading:
"Error uploading file to Garmin Connect:  invalid character 'w' looking for beginning of value"

Looks like the same:
https://github.com/petergardfjall/garminexport/issues/84

Best Regards,
Robert

**Comment by clyra** [comment]
I'm getting this error too :-(

**Comment by RobertWojtowicz** [comment]
Problem solved you need to compile version 2.2 with new version of Abrander module: https://github.com/abrander/garmin-connect/issues/17#issuecomment-1002265395

On my project where I use this awsome software (bodycomposition), I make available fixed version (compiled):
https://github.com/RobertWojtowicz/miscale2garmin

@davidkroell
Please update on your project page with the new version :)

**Comment by RobertWojtowicz** [comment]
I'm opening case for uploading a new version, just for information.

**Comment by davidkroell** [comment]
Hi @RobertWojtowicz, thanks for your work.
A new release is available: [v2.2.1](https://github.com/davidkroell/bodycomposition/releases/tag/v2.2.1)
