### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#2]
Missing function:
Physique Rating
Visceral Fat
Metabolic Age
Caloric Intake

Please, add them.

Best Regards,
Robert

**Comment by davidkroell** [comment]
Thank you for your attention, @Jufo84,

why do you want these changes to be made?
These values are not shown in Garmin Connect as far as I know.

Best Regards,
David

**Comment by RobertWojtowicz** [comment]
They are visible and partly (missing only Caloric Intake) synchronized by Weight Logger to Garmin Connect (https://github.com/kochka/WeightLogger):
![garmin3](https://user-images.githubusercontent.com/19271127/87128385-cfc30d80-c28f-11ea-9eab-bee311d0284b.png)

I have a plan to connect this solution https://github.com/rando-calrissian/esp32_xiaomi_mi_2_hass with your program to automatically send data from Xiaomi to Garmin Connect :)

Functionality with ESP32 already works:
![lacgbnpjkeebbgjp](https://user-images.githubusercontent.com/19271127/87130323-fafb2c00-c292-11ea-873b-ac4abd91879e.png)

**Comment by davidkroell** [comment]
Ah ok, thanks for your explanation, I've never really noticed these values in the web frontend, because I mainly use the Android app.
Your idea of connecting things sounds just great and seems to be very interesting. Is this project somewhere available on Github?

I assume you do not have knowledge of Golang, do you?
I'll work on this feature soon, it should not be that time-consuming.

Regards,
David

**Comment by RobertWojtowicz** [comment]
I don't know yet how to do it, probably based partly on https://github.com/rando-calrissian/esp32_xiaomi_mi_2_hass/blob/master/appdaemon/apps/xiaomi_scale.py wants this data to be sent by your program . I will probably create a project in github (I haven't done it yet), but only when I have your part complete,

I'm not a programmer, sometimes I stick something together :)

Best Regards,
Robert

**Comment by davidkroell** [comment]
I'm currently working on this feature, but the caloric intake doesn't get recognized, same as in your screenshot.

I also found out that those fields do not show up, when there are no values behind them, like it always was in my case

Regards,
David

**Comment by RobertWojtowicz** [comment]
Weight Logger APP has the same problem, it cannot send the Caloric Intake parameter, maybe it is not possible yet :(

Best Regards,
Robert
