### ISSUE TITLE
Some parameters are not synchronizing

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#3]
Some parameters are not synchronizing:
--physiqueRating
--visceralFat
--physiqueRating
--metabolicAge

These parameters are synchreonized incorrectly:
--bone - for example it should be 2.6 and it is 1.5
![err](https://user-images.githubusercontent.com/19271127/87188697-95895880-c2ef-11ea-96a7-eb495aef6bfd.png)

**Comment by davidkroell** [comment]
Can you share the exact command you used?
make sure you use the bone mass in percent, as the documentation shows

**Comment by RobertWojtowicz** [comment]
./bodycomposition upload --bone 2.6 --email [email] --fat 13.6 --hydration 59.2 --metabolicAge 21 --muscle 47.4 --password [password] --physiqueRating 5 --visceralFat 5 --weight 58.4

Ok, bone mass in percent, How to use in kg?

**Comment by davidkroell** [comment]
ok, this explains why you get 1.5 at your bone mass, as this is in percent (58.4*0,026 = 1.5 kilograms)
same is true for the skeletal muscle mass but i think there is the error somewhere else, when you get 47.7kg of muscle with a total weight of about 60 kilograms, again a percent issue 47% of ~60 kilograms is about 27 kilograms muscle

**Comment by davidkroell** [comment]
> Ok, bone mass in percent, How to use in kg?

There is currently no functionality to use in kg, maybe I add this in some time or you calculate the percent yourself

**Comment by RobertWojtowicz** [comment]
> There is currently no functionality to use in kg, maybe I add this in some time or you calculate the percent yourself

Ok, no problem, I already know how to convert :)

**Comment by davidkroell** [comment]
Make sure you also check muscle mass, 47.7kg is a litte bit unrealistic with about 60 kilos
