### ISSUE TITLE
Lates version 1.1.3 not working :(

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#4]
In both Windows and Linux, the sending attempt ends with such errors:

panic: username and/or password not recognized

goroutine 1 [running]:
github.com/davidkroell/bodycomposition.BodyComposition.uploadFitFile(0x54248e37, 0xbfba4f5c, 0xd82bf, 0x0, 0x877f200, 0x33333333, 0x404d3333, 0x33333333, 0x402b3333, 0x9999999a, ...)
        /home/davidk/go/src/github.com/davidkroell/bodycomposition/main.go:74 +0xc2
github.com/davidkroell/bodycomposition.BodyComposition.UploadWeight(0x54248e37, 0xbfba4f5c, 0xd82bf, 0x0, 0x877f200, 0x33333333, 0x404d3333, 0x33333333, 0x402b3333, 0x9999999a, ...)
        /home/davidk/go/src/github.com/davidkroell/bodycomposition/main.go:92 +0x185
github.com/davidkroell/bodycomposition/cmd.glob..func1(0x8738fa0, 0x9012280, 0x0, 0x14)
        /home/davidk/go/src/github.com/davidkroell/bodycomposition/cmd/upload.go:45 +0x3a5
github.com/spf13/cobra.(*Command).execute(0x8738fa0, 0x90121e0, 0x14, 0x14, 0x8738fa0, 0x90121e0)
        /home/davidk/go/src/github.com/spf13/cobra/command.go:845 +0x1f1
github.com/spf13/cobra.(*Command).ExecuteC(0x8738e40, 0x903e070, 0x0, 0x1)
        /home/davidk/go/src/github.com/spf13/cobra/command.go:946 +0x270
github.com/spf13/cobra.(*Command).Execute(...)
        /home/davidk/go/src/github.com/spf13/cobra/command.go:886
github.com/davidkroell/bodycomposition/cmd.Execute()
        /home/davidk/go/src/github.com/davidkroell/bodycomposition/cmd/root.go:24 +0x24
main.main()
        /home/davidk/go/src/github.com/davidkroell/bodycomposition/cmd/bodycomposition/main.go:8 +0x17

**Comment by davidkroell** [comment]
I know, I currently have build issues,
Release 1.2.7 is fully operational (just tested on Linux)

**Comment by RobertWojtowicz** [comment]
OK, it works now

Thank you :)
