### ISSUE TITLE
Error: unknown flag: --metabolicAge

### ISSUE THREAD

**Issue by RobertWojtowicz** [davidkroell/bodycomposition#8]
Problem in new version v2.0.0-rc1

By the way, I can add Caloric Intake ?

**Comment by RobertWojtowicz** [comment]
ok you change to:
--metabolic-age
--physique-rating

**Comment by davidkroell** [comment]
Yeah, i changed the CLI interface, therefore release candidate for version 2

See changelog: https://github.com/davidkroell/bodycomposition/releases/tag/v2.0.0-rc1

Please battle-test it

> By the way, I can add Caloric Intake ?

How do you do this? I have not done anything about this.

**Comment by davidkroell** [comment]
Btw: parameter `--max-tries` is now available check this out

**Comment by RobertWojtowicz** [comment]
> > By the way, I can add Caloric Intake ?
> 
> How do you do this? I have not done anything about this.

I wrote about it here: https://github.com/davidkroell/bodycomposition/issues/2

**Comment by davidkroell** [comment]
This is not possible yet, but maybe I can do something about it.
